version: "3.7"

services:
  # Backend API
  alchemy-type-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/alchemy-type-api
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/alchemy-type-api
  # Postgres
  postgres:
    env_file:
      - ./.env
    build: ./postgres
    ports:
      - "5432:5432"
  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
